---

- name: 'MariaDb - Installation'
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: present

- name: 'MariaDb - Restarting/Enabling'
  service:
    name: mariadb
    state: restarted
    enabled: yes

- name: 'MariaDb - Resetting Root Password'
  ignore_errors: yes
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
    
- name: 'MariaDb - Removing Anonymous Users'
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ''
    host_all: yes
    state: absent
      
- name: 'MariaDb - Creating Additional Database'
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ mysql_database }}"
    state: present
      
      
- name: 'MariaDb - Creating Additioanl User and Privileges'
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    host: localhost
    password: "{{ mysql_password}}"
    priv: "{{mysql_database}}.*:ALL"
